force-app/main/default/objects/Case/fields/Open_Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Open_Sales_Order__c</fullName>
    <label>Open Sales Order</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Status__c</fullName>
    <label>Transaction Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EFT_Transaction_Status__c/EFT_Transaction_Status__c.object-meta.xml
<CustomObject>
    <label>EFT Transaction Status</label>
    <nameField>
        <displayFormat>ETS-{000000}</displayFormat>
        <label>EFT Transaction Status Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EFT Transaction Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EFT_Transaction_Status__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>EFT Transaction Status</relationshipLabel>
    <relationshipName>EFT_Transaction_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EFT_Transaction_Status__c/fields/SalesHeader__c.field-meta.xml
<CustomField>
    <fullName>SalesHeader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SalesHeader</label>
    <referenceTo>SalesHeader__c</referenceTo>
    <relationshipLabel>EFT Transaction Status</relationshipLabel>
    <relationshipName>EFT_Transaction_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EFT_Transaction_Status__c/fields/Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Status__c</fullName>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesHeader__c/SalesHeader__c.object-meta.xml
<CustomObject>
    <label>SalesHeader</label>
    <nameField>
        <displayFormat>SH-{000000}</displayFormat>
        <label>SalesHeader Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SalesHeader</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesHeader__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SalesHeader</relationshipLabel>
    <relationshipName>SalesHeader</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesHeader__c/fields/Bill_to_City__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_City__c</fullName>
    <label>Bill to City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesHeader__c/fields/Bill_to_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Postal_Code__c</fullName>
    <label>Bill to Postal Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesHeader__c/fields/Bill_to_State__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_State__c</fullName>
    <label>Bill to State</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesHeader__c/fields/Bill_to_street__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_street__c</fullName>
    <label>Bill to street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesHeader__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>SalesHeader</relationshipLabel>
    <relationshipName>SalesHeader</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesHeader__c/fields/Ship_to_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Ship_to_Postal_Code__c</fullName>
    <label>Ship to Postal Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesHeader__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SalesHeaderCrossShipHandler.cls
public class SalesHeaderCrossShipHandler {
     
    
    public static void CrossShipMethod(List<SalesHeader__c> slist){
        List<Case> caselist=new list<Case>();
    for(SalesHeader__c sh:slist){
        EFT_Transaction_Status__c eft=new EFT_Transaction_Status__c();
        Case c=new Case();
        if(sh.Status__c=='Open'&& sh.Total_Amount__c>='300'&& sh.Bill_to_City__c!=sh.Ship_to_City__c || sh.Bill_to_Postal_Code__c!=sh.Ship_to_Postal_Code__c ||
                                                              sh.Bill_to_State__c!=sh.Ship_to_State__c || sh.Bill_to_street__c!=sh.Ship_to_Street__c){
                                                                  
              c.AccountId=sh.Account__c;
              c.ContactId=sh.Contact__c;
              c.Origin='Internal';
              c.Reason='Unable to Cross Ship';
              c.Priority='Medium';
              c.Status='New';
              c.Subject=sh.Account__c+''+c.Type;
              c.Type='Unable to Cross Ship';
              c.Open_Sales_Order__c=sh.Id;
              c.Transaction_Status__c=eft.Transaction_Status__c;
              c.Order_Date__c=eft.Transaction_Date__c;
              caselist.add(c);
              
         }
    }
    insert caselist;
    }
}