force-app/main/default/objects/Case/fields/Open_Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Open_Sales_Order__c</fullName>
    <label>Open Sales Order</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sales_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Number__c</fullName>
    <label>Sales Order Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Status__c</fullName>
    <label>Transaction Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EFT_Transaction_Status__c/EFT_Transaction_Status__c.object-meta.xml
<CustomObject>
    <label>EFT Transaction Status</label>
    <nameField>
        <displayFormat>ETS-{000000}</displayFormat>
        <label>EFT Transaction Status Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EFT Transaction Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EFT_Transaction_Status__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>EFT Transaction Status</relationshipLabel>
    <relationshipName>EFT_Transaction_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EFT_Transaction_Status__c/fields/SalesHeader__c.field-meta.xml
<CustomField>
    <fullName>SalesHeader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SalesHeader</label>
    <referenceTo>SalesHeader__c</referenceTo>
    <relationshipLabel>EFT Transaction Status</relationshipLabel>
    <relationshipName>EFT_Transaction_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EFT_Transaction_Status__c/fields/Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Status__c</fullName>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesHeader__c/SalesHeader__c.object-meta.xml
<CustomObject>
    <label>SalesHeader</label>
    <nameField>
        <displayFormat>SH-{000000}</displayFormat>
        <label>SalesHeader Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SalesHeader</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesHeader__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SalesHeader</relationshipLabel>
    <relationshipName>SalesHeader</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesHeader__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>SalesHeader</relationshipLabel>
    <relationshipName>SalesHeader</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesHeader__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>SalesHeader</relationshipLabel>
    <relationshipName>SalesHeader</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesHeader__c/fields/Names__c.field-meta.xml
<CustomField>
    <fullName>Names__c</fullName>
    <label>Names</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EFTTransStatusHandler.cls
public class EFTTransStatusHandler {
    
    public static void eftMethod(List<EFT_Transaction_Status__c> eftlist){
        List<Case> caselist=new list<Case>();
    
    for(EFT_Transaction_Status__c eftt:eftlist){
        
        
        for(EFT_Transaction_Status__c eft:[Select id,Method_Name__c,Transaction_Date__c,SalesHeader__r.Names__c,Transaction_Status__c,SalesHeader__c,SalesHeader__r.Contact__c,SalesHeader__r.Account__c,SalesHeader__r.Status__c from EFT_Transaction_Status__c WHERE id in:trigger.new]){
        if(eft.Method_Name__c=='Credit Card Address Verify'&& eft.Transaction_Status__c=='Declined'&& eft.SalesHeader__r.Status__c=='Open'){
            
            Case cs=new Case();
            cs.AccountId=eft.SalesHeader__r.Account__c;
            cs.ContactId=eft.SalesHeader__r.Contact__c;
            cs.Origin='Internal';
            cs.Reason='Address Did Not Verify';
            cs.Priority='High';
            cs.Status='New';
            String sccname=[Select Name from Account WHERE id=:eft.SalesHeader__r.Account__c].Name;
            cs.Subject=sccname+' '+cs.Type;
            cs.Type='Address Did Not Verify';
            cs.Open_Sales_Order__c=eft.SalesHeader__c;
            cs.Transaction_Status__c=eft.Transaction_Status__c;
            cs.Sales_Order_Number__c=eft.SalesHeader__r.Names__c;
            cs.Order_Date__c=eft.Transaction_Date__c;
            caselist.add(cs);
        
        }
    }
   
    insert caselist;
    
    }
    }

}