force-app/main/default/objects/EFT_Transaction_Status__c/EFT_Transaction_Status__c.object-meta.xml
<CustomObject>
    <label>EFT Transaction Status</label>
    <nameField>
        <displayFormat>ETS-{000000}</displayFormat>
        <label>EFT Transaction Status Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EFT Transaction Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EFT_Transaction_Status__c/fields/SalesHeader__c.field-meta.xml
<CustomField>
    <fullName>SalesHeader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SalesHeader</label>
    <referenceTo>SalesHeader__c</referenceTo>
    <relationshipLabel>EFT Transaction Status</relationshipLabel>
    <relationshipName>EFT_Transaction_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EFT_Transaction_Status__c/fields/Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Status__c</fullName>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesHeader__c/SalesHeader__c.object-meta.xml
<CustomObject>
    <label>SalesHeader</label>
    <nameField>
        <displayFormat>SH-{000000}</displayFormat>
        <label>SalesHeader Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SalesHeader</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesHeader__c/fields/Bill_to_City__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_City__c</fullName>
    <label>Bill to City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesHeader__c/fields/Bill_to_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Postal_Code__c</fullName>
    <label>Bill to Postal Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesHeader__c/fields/Bill_to_State__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_State__c</fullName>
    <label>Bill to State</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesHeader__c/fields/Bill_to_street__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_street__c</fullName>
    <label>Bill to street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesHeader__c/fields/Names__c.field-meta.xml
<CustomField>
    <fullName>Names__c</fullName>
    <label>Names</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesHeader__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EFTTransStatusHandlerTest.cls
/*
 * class Name:EFTTransStatusHandlerTest
 * Description:This class is return to cover EFTTransStatusHandler.
 * Created by:Ashlesha 
 * Created Date:05/04/2021
 */

@isTest
public class EFTTransStatusHandlerTest {
    
    @isTest static void Eftmethod(){
        
        EFT_Transaction_Status__c eft=new EFT_Transaction_Status__c();
        eft.Method_Name__c='Credit Card Address Verify';
        eft.Transaction_Status__c='Declined';
        insert eft;
        
         SalesHeader__c s=new SalesHeader__c();
        s.Status__c='Open';
        s.Total_Amount__c='400';
        s.Names__c='Bill to customer';
        s.Bill_to_City__c='Pune';
        s.Bill_to_Postal_Code__c='101';
        s.Bill_to_State__c='Maharashtra';
        s.Bill_to_street__c='NIT';
        insert s;
        
       /* SalesHeader__c sh=new SalesHeader__c();
           sh.Status__c='Open';
           sh.Total_Amount__c='500';
           insert sh;
        
        EFT_Transaction_Status__c ef=new EFT_Transaction_Status__c();
       
       ef.Transaction_Status__c='Declined';
       ef.Method_Name__c='Credit Card Address Verify';
       ef.SalesHeader__c=sh.id;
       insert ef;*/
      
       // Test.startTest();
          List<EFT_Transaction_Status__c> elist=new list<EFT_Transaction_Status__c>();
         
            EFTTransStatusHandler.eftMethod(elist);
        //Test.stopTest();
            
    }

}