force-app/main/default/objects/Account/fields/EDomain__c.field-meta.xml
<CustomField>
    <fullName>EDomain__c</fullName>
    <label>EDomain</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Email_Domain__c.field-meta.xml
<CustomField>
    <fullName>Email_Domain__c</fullName>
    <label>Email Domain</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EDomainNewHandler.cls
public class EDomainNewHandler {
    
    public static void DomainName(List<Contact> clist){
        
        List<string> conlist=new list<string>();
        for(Contact ct:clist){
        conlist.add(ct.Email_Domain__c);
    }
    List<Account> accountlist=[Select id,EDomain__c from Account where EDomain__c LIKE : conlist];
    Map<string,id> mapaccount=new Map<string,id>();
    for(Account acc:accountlist){
        for(String dom:acc.EDomain__c.split(',')){
            mapaccount.put(dom,acc.Id);
        }
        
    }
    for(Contact ct:clist){
        if(mapaccount.get(ct.Email_Domain__c)!=null){
            ct.AccountId=mapaccount.get(ct.Email_Domain__c);
        }
    }
    }

}